name: Build Ren'Py Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

<<<<<<< HEAD
=======
env:
  RENPY_VERSION: "8.5.3"

>>>>>>> d1ff6fe3faa33d9a5a372f64fb79f6af7808e343
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Ren'Py
        run: |
<<<<<<< HEAD
          wget https://www.renpy.org/dl/8.5.4/renpy-8.5.4-sdk.tar.bz2
          tar -xjf renpy-8.5.4-sdk.tar.bz2

      - name: Build
        run: |
          mkdir -p dist

          ./renpy-8.5.4-sdk/renpy.sh launcher distribute "$GITHUB_WORKSPACE" \
=======
          wget "https://www.renpy.org/dl/${RENPY_VERSION}/renpy-${RENPY_VERSION}-sdk.tar.bz2"
          tar -xjf "renpy-${RENPY_VERSION}-sdk.tar.bz2"

      - name: Build
        run: |
          mkdir -p "$GITHUB_WORKSPACE/dist"

          cd "$GITHUB_WORKSPACE/renpy-${RENPY_VERSION}-sdk"

          ./renpy.sh launcher distribute "$GITHUB_WORKSPACE" \
>>>>>>> d1ff6fe3faa33d9a5a372f64fb79f6af7808e343
            --destination "$GITHUB_WORKSPACE/dist" \
            --package pc \
            --package mac

<<<<<<< HEAD
      - name: Create Release
=======
      - name: Create GitHub Release
>>>>>>> d1ff6fe3faa33d9a5a372f64fb79f6af7808e343
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
<<<<<<< HEAD
            dist/* \
=======
            "$GITHUB_WORKSPACE"/dist/* \
>>>>>>> d1ff6fe3faa33d9a5a372f64fb79f6af7808e343
            --verify-tag \
            --generate-notes \
            --title "${GITHUB_REF_NAME}"